[package]
name = "step_3_11"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
num_cpus = "1.16.0"
reqwest = "0.11.22"
tokio = { version = "1.35.0", features = ["full"] }
